version: '3'

services:
  db:
    env_file:
      - ./database/.env
    build:
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
      context: ./database
      dockerfile: Dockerfile
    image: db
    ports:
      - 8000:8000